#pragma once

namespace RE
{
	class CHANGE_TYPES
	{
	public:
		enum CHANGE_TYPE : std::uint32_t
		{
			kFormCreated = 0,
			kFormFlags = 1u << 0,
			kRefrMove = 1u << 1,
			kRefrHavokMove = 1u << 2,
			kRefrCellChange = 1u << 3,
			kRefrScale = 1u << 4,
			kRefrInventory = 1u << 5,
			kRefrExtraOwnership = 1u << 6,
			kRefrBaseObject = 1u << 7,
			kRefrExtraLinkRef = 1u << 8,
			kRefrExtraWorkshop = 1u << 9,
			kRefrExtraGameOnly = 1u << 31,
			kRefrExtraCreatedOnly = 1u << 30,
			kRefrExtraEncounterZone = 1u << 29,
			kRefrAnimation = 1u << 28,
			kRefrLeveledInventory = 1u << 27,
			kRefrExtraActivatingChildren = 1u << 26,
			kRefrPromoted = 1u << 25,
			kActorLifestate = 1u << 10,
			kActorExtraPackageData = 1u << 11,
			kActorExtraMerchantContainer = 1u << 12,
			kActorPermanentModifiers = 1u << 23,
			kActorOverrideModifiers = 1u << 22,
			kActorDamageModifiers = 1u << 21,
			kActorTempModifiers = 1u << 20,
			kActorDispositionModifiers = 1u << 19,
			kActorExtraLeveledActor = 1u << 18,
			kActorExtraDismemberedLimbs = 1u << 17,
			kObjectExtraItemData = 1u << 10,
			kObjectExtraAmmo = 1u << 11,
			kObjectExtraLock = 1u << 12,
			kObjectForceMove = 1u << 13,
			kObjectOpenState = 1u << 23,
			kObjectOpenDefaultState = 1u << 22,
			kObjectEmpty = 1u << 21,
			kDoorExtraTeleport = 1u << 17,
			kQuestFlags = 1u << 1,
			kQuestScriptDelay = 1u << 2,
			kQuestStages = 1u << 31,
			kQuestScript = 1u << 30,
			kQuestObjectives = 1u << 29,
			kQuestRunData = 1u << 28,
			kQuestInstances = 1u << 27,
			kQuestAlreadyRun = 1u << 26,
			kTopicSaidPlayer = 1u << 30,
			kTopicSaidOnce = 1u << 31,
			kRelationshipData = 1u << 1,
			kLocationSpecRefs = 1u < 28,
			kLocationNewRefs = 1u << 29,
			kLocationKeywordData = 1u << 30,
			kLocationCleared = 1u << 31,
			kNoteRead = 1u << 31,
			kCellSeenData = 1u << 31,
			kCellDetachTime = 1u << 30,
			kCellExteriorChar = 1u << 29,
			kCellExteriorShort = 1u << 28,
			kCellFlags = 1u << 1,
			kCellFullname = 1u << 2,
			kCellOwnership = 1u << 3,
			kFactionFlags = 1u << 1,
			kFactionReactions = 1u << 2,
			kFactionVendorData = 1u << 30,
			kFactionCrimeCounts = 1u << 31,
			kPackageNeverRun = 1u << 31,
			kPackageWaiting = 1u << 30,
			kBaseObjectValue = 1u << 1,
			kBaseObjectFullName = 1u << 2,
			kBookTeaches = 1u << 5,
			kBookRead = 1u << 6,
			kTalkingActivatorSpeaker = 1u << 23,
			kActorBaseData = 1u << 1,
			kActorBaseAttributes = 1u << 2,
			kActorBaseAIData = 1u << 3,
			kActorBaseSpellList = 1u << 4,
			kActorBaseFullName = 1u << 5,
			kActorBaseFactions = 1u << 6,
			kNPCSkills = 1u << 9,
			kNPCClass = 1u << 10,
			kNPCFace = 1u << 11,
			kNPCDefaultOutfit = 1u << 12,
			kNPCSleepOutfit = 1u << 13,
			kNPCBodyScales = 1u << 14,
			kNPCRace = 1u << 25,
			kNPCGender = 1u << 24,
			kCreatureSkills = 1u << 9,
			kClassTagSkills = 1u << 1,
			kEncounterZoneFlags = 1u << 1,
			kEncounterZoneGameData = 1u << 31,
			kQuestNodeRunTime = 1u << 31,
			kSceneActive = 1u << 31,
			kFormListAddedForm = 1u << 31,
			kLeveledListAddedObject = 1u << 31,
			kIngredientUse = 1u << 31,
			kINRMergeTarget = 1u << 31
		};
	};
	using CHANGE_TYPE = CHANGE_TYPES::CHANGE_TYPE;
}
